name: Build Container

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Cypress
    if: github.repository == 'xibosignage/xibo-cms'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          docker build -f Dockerfile.cypress . -t xibosignage/xibo-cms:cypress
      - name: Push
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push xibosignage/xibo-cms:cypress