name: Test Suite

on: [pull_request]

jobs:
  test-suite:
    name: Build Containers and Run Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Pull
        run: |
          docker pull mysql:5.6
          docker pull xibosignage/xibo-xmr:latest
          docker pull xibosignage/xibo-cms:develop
          docker pull xibosignage/xibo-cms:cypress
      - name: Get Diff
        run: |
          git fetch origin ${GITHUB_BASE_REF}
          git diff origin/${GITHUB_BASE_REF} > diff.txt
          git diff origin/${GITHUB_BASE_REF} --name-only --diff-filter=ACMR -- "*.php" > files.txt
      - name: Build
        run: |
          docker build . -f Dockerfile.ci -t cms-web --build-arg GIT_COMMIT=${GITHUB_SHA}
      - name: Run
        run: |
          docker run --name cms-db -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=cms -e MYSQL_USER=cms -e MYSQL_PASSWORD=jenkins -d mysql:5.6
          docker run --name cms-xmr -d xibosignage/xibo-xmr:latest
          docker run --name cms-web -e MYSQL_USER=cms -e MYSQL_PASSWORD=jenkins -e XIBO_DEV_MODE=true -e XMR_HOST=cms-xmr --link cms-db:db --link cms-xmr:50001 -d cms-web
      - name: Wait for CMS
        run: |
          docker exec -t cms-web /bin/bash -c "/usr/local/bin/wait-for-command.sh -q -t 300 -c \"nc -z localhost 80\""
          docker cp cms-web:/var/www/cms/web/settings.php web/settings.php
          docker exec -t cms-web /bin/bash -c "chown -R apache.apache /var/www/cms"
          docker exec --user apache -t cms-web /bin/bash -c "cd /var/www/cms; /usr/bin/php bin/run.php 1"
          sleep 5
      - name: Run Code Sniffer
        run: |
          if [[ -s "files.txt" ]]; then
            docker exec --user apache -t cms-web /bin/bash -c "cd  /var/www/cms/; vendor/bin/phpcs --standard=vendor/xibosignage/support/src/Standards/xibo_ruleset.xml --report=json --file-list=files.txt > phpcs.json || true"
            docker exec --user apache -t cms-web /bin/bash -c "cd  /var/www/cms/; vendor/bin/diffFilter --phpcs diff.txt phpcs.json"
          fi
